
{
    'name': 'Warehouse Internal Transfers User to Validate',
    'version': '6.0.0',
    'category': 'Warehouse',
    "author": 'Zero Systems',
    "company": 'Zero for Information Systems',
    "website": "https://www.erpzero.com",
    "email": "sales@erpzero.com",
    "sequence": 0,
    'license': 'OPL-1',
    'live_test_url': 'https://www.youtube.com/playlist?list=PLXFpENL3b6WU9TzMdawrHJsUBqMDXkcbn',
    'summary': """Validate of the store transfer is the right of the user who has rights on the store transferred to him only""",
    'description': """Validate of the store transfer is the right of the user who has rights on the store transferred to him only""",
    'depends': ['base','stock'],
    'data': [
        'views/view.xml',
    ],
    'images': ['static/description/internal_transfers.png'],
    'installable': True,
    'auto_install': False,
    'application': False,
    "price": 50.0,
    "currency": 'EUR',
}
